'use strict';

var gulp = require('gulp'),
    debug = require('gulp-debug'),
    inject = require('gulp-inject'),
    tsc = require('gulp-typescript'),
    tslint = require('gulp-tslint'),
    sourcemaps = require('gulp-sourcemaps'),
    Config = require('./gulpfile.config'),
    del = require('del');

var config = new Config();

// Generates the app.d.ts references file dynamically from all application *.ts files.
////////////////////////////////////
gulp.task('gen-ts-refs', function () {
    var target = gulp.src(config.appTypeScriptReferences);
    var sources = gulp.src([config.allTypeScript], {read: false});
    function _transform(filepath) {
      return '/// <reference path="../..' + filepath + '" />';
    }
    return target
      .pipe(inject(sources, {
        starttag: '//{',
        endtag: '//}',
        transform: _transform}))
      .pipe(gulp.dest(config.typings));
});

// Lint all custom TypeScript files.
////////////////////////////////////
gulp.task('ts-lint', function () {
    return gulp
      .src(config.allTypeScript)
      .pipe(tslint())
      .pipe(tslint.report('prose'));
});


// Compile TypeScript.
// Include references to library and app .d.ts files.
////////////////////////////////////
gulp.task('compile-ts', function () {
    var sourceTsFiles = [
      config.allTypeScript,                //path to typescript files
      config.libraryTypeScriptDefinitions, //reference to library .d.ts files
      config.appTypeScriptReferences       //reference to app.d.ts files
    ];
    var tsResult = gulp.src(sourceTsFiles)
      .pipe(sourcemaps.init())
      .pipe(tsc({
        target: 'ES5',
        declarationFiles: false,
        noExternalResolve: true
      }))
      .dts.pipe(gulp.dest(config.tsOutputPath));
      .js.pipe(sourcemaps.write('.'))
      .pipe(gulp.dest(config.tsOutputPath));
    return tsResult
});

// Remove all generated JavaScript files from TypeScript compilation.
////////////////////////////////////
gulp.task('clean-ts', function (cb) {
  var typeScriptGenFiles = [
    config.tsOutputPath,            // path to generated JS files
    config.sourceApp +'**/*.js',    // path to all JS files auto generated by editor
    config.sourceApp +'**/*.js.map' // path to all source-map files auto generated by editor
  ];

  // delete the files
  del(typeScriptGenFiles, cb);
});

// Watch for changes
////////////////////////////////////
gulp.task('watch', function() {
    gulp.watch(
      [config.allTypeScript],
      ['ts-lint', 'compile-ts', 'gen-ts-refs']
    );
});

// Default task
////////////////////////////////////
gulp.task('default',
  ['ts-lint', 'compile-ts', 'gen-ts-refs', 'watch']
);
